<?php
header('Content-Type: application/json');

// 1. Connection
$conn = new mysqli("localhost", "root", "", "project");

if ($conn->connect_error) {
    echo json_encode(["success" => false, "message" => "Database connection failed"]);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['user_name'])) {
    
    // 2. Data Collection
    $name     = $_POST['user_name'];
    $address  = $_POST['user_address'];
    $contact  = $_POST['user_contact'];
    $role_id  = intval($_POST['role_id']);
    $shop_id  = intval($_POST['shop_id']);
    $email    = $_POST['login_email'];
    $password = $_POST['login_password'];

    // Security check
    if ($role_id === 1) {
        echo json_encode(["success" => false, "message" => "Unauthorized role assignment."]);
        exit;
    }

    // 3. Password Hashing
    $hashed_password = password_hash($password, PASSWORD_DEFAULT);

    // 4. Start Transaction
    $conn->begin_transaction();

    try {
        // STEP A: Insert into 'login' table FIRST (The Boss generates the ID)
        $stmt_login = $conn->prepare("INSERT INTO login (Login_name, Login_email, Login_contact, Login_password, Role_id, Reg_date) VALUES (?, ?, ?, ?, ?, NOW())");
        $stmt_login->bind_param("ssssi", $name, $email, $contact, $hashed_password, $role_id);
        $stmt_login->execute();
        
        // STEP B: Capture the ID generated by the login table
        $master_id = $conn->insert_id; 

        // STEP C: Insert into 'user' table using that SAME ID
        // We manually insert $master_id into BOTH User_id and Login_id
        $stmt_user = $conn->prepare("INSERT INTO user (User_id, User_name, User_address, User_contact, Role_id, Shop_id, Login_id) VALUES (?, ?, ?, ?, ?, ?, ?)");
        $stmt_user->bind_param("isssiii", $master_id, $name, $address, $contact, $role_id, $shop_id, $master_id);
        $stmt_user->execute();

        // 5. Success!
        $conn->commit();
        echo json_encode(["success" => true, "assigned_id" => $master_id]);

    } catch (Exception $e) {
        // 6. Failure! Rollback so we don't have a login without a user
        $conn->rollback();
        echo json_encode(["success" => false, "message" => "Database Error: " . $e->getMessage()]);
    }

    $stmt_login->close();
    $stmt_user->close();
} else {
    echo json_encode(["success" => false, "message" => "Invalid Request"]);
}

$conn->close();
?>